### ISSUE TITLE
An error has occurred. Check your logs or contact the app author for clarification.

### ISSUE THREAD

**Issue by mattbarter** [bence-szalai/Cell-death-signatures#18]
Hi,
I've seen the other thread and have the gene name column as 'gene' but i'm still getting this error when i click through to the Cell Viability tab.
My data looks in the right format:
![Capture](https://github.com/bence-szalai/Cell-death-signatures/assets/36448041/5550177b-2e3a-4e28-b4a8-26b5b2b5150b)
I've tried removing any rows that had 0 for the log fold change as well as any that were getting converted to scientific notation upon upload but it doesn't seem to help.
[Logfold changes.csv](https://github.com/bence-szalai/Cell-death-signatures/files/14101502/Logfold.changes.csv)
[Logfold_changes_Day1_above0.01.csv](https://github.com/bence-szalai/Cell-death-signatures/files/14101505/Logfold_changes_Day1_above0.01.csv)
[Logfold_changes_no_0s.csv](https://github.com/bence-szalai/Cell-death-signatures/files/14101506/Logfold_changes_no_0s.csv)
I uploaded the original file and these with rows removed in case you want to try to work it out.
Do all the gene names need to match exactly to what is in the achilles or CTRP lists?
Thanks,
Matt

**Comment by bence-szalai** [comment]
Hi @mattbarter,

thanks for using CEVIChE. The problem is that your gene expression matrix contains duplicated genes (rows) - e.g. 'SQSTM1', 'FDFT1' etc.. Gene names does not have to match with Achilles / CTRP model's gene names, however this duplication makes problem. I just averaged the expression of the duplicated genes, and now it works for me in the application.

[Logfold_changes_nodupl.csv](https://github.com/bence-szalai/Cell-death-signatures/files/14109718/Logfold_changes_nodupl.csv)

Hope it works for you also. Best,

Bence

**Comment by mattbarter** [comment]
> Hi @mattbarter,
> 
> thanks for using CEVIChE. The problem is that your gene expression matrix contains duplicated genes (rows) - e.g. 'SQSTM1', 'FDFT1' etc.. Gene names does not have to match with Achilles / CTRP model's gene names, however this duplication makes problem. I just averaged the expression of the duplicated genes, and now it works for me in the application.
> 
> [Logfold_changes_nodupl.csv](https://github.com/bence-szalai/Cell-death-signatures/files/14109718/Logfold_changes_nodupl.csv)
> 
> Hope it works for you also. Best,
> 
> Bence

Ah thanks Bence. Clearly I didn't think of that. Those pesky transcript variants!
Thanks for the quick reply, Matt
